name: Build Dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-and-deploy-dev:
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run prerender

      - name: Deploy to gh-pages-dev branch
        uses: JamesIves/github-pages-deploy-action@v4.4.3

        with:
          branch: gh-pages-dev
          folder: build
